export enum HistoryEventType {
  LOAN_BORROWED = 'LOAN_BORROWED',
  LOAN_RETURNED = 'LOAN_RETURNED',
  RESERVATION_CREATED = 'RESERVATION_CREATED',
  RESERVATION_CANCELLED = 'RESERVATION_CANCELLED',
  RESERVATION_APPROVED = 'RESERVATION_APPROVED',
  RESERVATION_REJECTED = 'RESERVATION_REJECTED',
  RESERVATION_EXPIRED = 'RESERVATION_EXPIRED',
  RESERVATION_CONVERTED_TO_LOAN = 'RESERVATION_CONVERTED_TO_LOAN',
}
